WIP Improving alpha diversity calculation
scikit-bio/scikit-bio pull request #2024
Opened 2024-05-12 19:22 UTC by qiyunzhu

@ebolyen This addresses the relevant issue #2014 . Now the alpha diversity metrics return `np.nan` instead of zero when the community is empty.

One relevant question is how to deal with one-taxon communities when calculating species evenness metrics. At present, `pielou_e` and `heip_e` return `np.nan`, whereas `simpson_e` returns 1. I tend to think 1 makes sense. Evenness should range between 0 and 1, in which 1 means all species have the same abundance (i.e., completely even). When there is only one species, it is guaranteed that evenness is maximized. On the other hand, it will not be ideal if a non-empty community returns a NaN value. What do you think?

@wasade This also improves how counts are validated. Specifically, it will remove zeros from the counts before calculating alpha diversity. This will save troubles in the downstream implementation of alpha diversity metrics. This will also permit efficiency improvement by directly feeding sparse matrices from BIOM into the calculation. However, the latter is not done yet. This needs further discussion. That being said, the current PR should be safe to use before the final solution.

Also cc'ing @mortonjt 

Please complete the following checklist:

* [x] I have read the [contribution guidelines](https://scikit.bio/contribute.html).

* [x] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied.

  - **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] This pull request does not include code, documentation, or other content derived from external source(s).

Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

2024-05-15 15:55 UTC, qiyunzhu commented
Hello @ebolyen would you like to comment on whether the consideration of edge cases (empty community, one-species community) is sane in this PR (see my comments above)? Also cc'ing @gregcaporaso

2024-06-08 22:39 UTC, qiyunzhu commented
Now there is a significant enrichment of the parameters and documentation of alpha diversity metrics.

2024-06-08 23:04 UTC, qiyunzhu commented
@wasade @mortonjt Here is a very large PR. I did some substantial amount of literature review in order to improve the calculation and documentation of all alpha diversity metrics. I wonder if either of you can do a quick sanity check of the technical side of my code (especially counts vector validation and transformation), while trusting my professionality in community ecology?

2024-06-11 21:19 UTC, mataton requested changes
Other than the windows tests failures which I commented on, everything looks good.

2024-06-11 21:19 UTC, mataton commented on skbio/diversity/tests/test_driver.py
>          expected = pd.Series([0], dtype=int)
`expected` should have `dtype=np.int64` to pass on Windows.

This is also true for lines 208 in `test_empty`, line 213 in `test_single_count_vector`, lines 255 and 262 in `test_sobs`, and line 315 in `test_no_ids` in this class.

2024-06-11 21:19 UTC, mataton commented on skbio/diversity/tests/test_driver.py
>          expected = pd.Series([0], dtype=int)
`dtype=np.int64`

2024-06-11 21:19 UTC, mataton commented on skbio/diversity/tests/test_driver.py
>          expected = pd.Series([0, 0], dtype=int)
`dtype=np.int64`.

2024-06-11 21:29 UTC, qiyunzhu commented
@mataton Thanks! I have made the edits you suggested.

2024-06-11 21:30 UTC, mataton approved these changes

2024-06-16 16:56 UTC, qiyunzhu commented
Let me merge this PR and move on.

2024-06-16 16:56 UTC, merged